### ISSUE TITLE
[Error  : Unity Log] 11/01/2022 08:09:05: No instances of Knarr found

### ISSUE THREAD

**Issue by majesticuni** [sbtoonz/Trader_2.0#11]
I created a new world, I did the commands of "find Knarr" and this is the error that popped up. I have the setting in cfg as default for the spawning as I wanted him to spawn only in Meadows as in description. I really love this mod because its simple and the voice inputs are just amazing. 

Is there something im doing wrong or is this broken still after update? Heard reports that serversync is still broken after update but havent tested that myself yet.

Does this also spawn him in on current worlds or does it need to be on a new world for him to spawn?

### Whether or not knarr should spawn using locationsystem
Setting type: Boolean
Default value: false
Should Knarr randomly spawn around your world? = false

**Comment by majesticuni** [comment]
There is also 2 names of Knarr showing when you do the " find Knarr" commands.

**Comment by sbtoonz** [comment]
if you are using Horems mod pack he places knarr a different way than the spawn code i wrote

**Comment by majesticuni** [comment]
> if you are using Horems mod pack he places knarr a different way than the spawn code i wrote

I only have Knarr added with this error, in my other profile I only have DoOrDie Monsters mod, but didnt try that yet

**Comment by majesticuni** [comment]
Just an update:
Installed ONLY Knarr, I went and made a brand new world, I did the "find Knarr" command and said no instances found.
set the config for Knarr spawn randomly around world to true, entered a new world, same thing no instances found.

**Comment by sbtoonz** [comment]
So

I just tested this 
I will fix the prompt feedback because if you open your map you will see knar has been marked with possible spawns on the map

**Comment by majesticuni** [comment]
> So
> 
> I just tested this I will fix the prompt feedback because if you open your map you will see knar has been marked with possible spawns on the map

Thats weird.... I was never able to see him so im not sure what happened, ill try the new update

**Comment by ElweThor** [comment]
I'm seeing I'm having the very same problem: in my Q&A thread I reported there was just a "No instance od knarr found" as a message but, looking into Log I can see it's an error. Not only: if I open the main map, and exclude all the pins, so to be able to see Traders only, I'm seeing my usual (standard/default) trader, but Knarr is shown nowhere (in the whole map).
