### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ShootToKillSTK** [sbtoonz/Trader_2.0#16]
Makes game very laggy while in inventory, and even worse when in chests/storage

**Comment by sbtoonz** [comment]
Which version are you on?

**Comment by sbtoonz** [comment]
https://www.youtube.com/watch?v=9Qne_jSSI9w&ab_channel=SBToonz

**Comment by sbtoonz** [comment]
closing as unable to replicate

**Comment by sbtoonz** [comment]
potentially was released before i moved this

2fc822954d2896272315946d54fc7e425d77bee5

**Comment by sbtoonz** [comment]
uploading 0.3.8 with this fix in place

**Comment by ShootToKillSTK** [comment]
Yes that seems to of fixed it nice
