### ISSUE TITLE
[Bug] - When Saving YML Contents && Selling via slider. Stack is improperly saved

### ISSUE THREAD

**Issue by insanepinky** [sbtoonz/Trader_2.0#17]
**Describe the bug**
Was doing some test selling with knarr and noticed he would gain more or less items than I sold to him. Context for the examples below: I have the config set so he'll buy Ruby in stacks of 1 for 20 coins (matching Haldor's vanilla price).

Example 1:
- Knarr has no Ruby. I have a full stack of 20.
- I click to sell Knarr a Ruby and select 1 from the slider. The message pops up saying "sold 19 Ruby for 20 x20".
- I check my inventory and see I now have 19 Ruby left and 20 Coins. I check Knarr's Buy inventory and he now has 19 Ruby when I only sold him 1.

Example 2:
- Knarr has no Ruby. I have a full stack of 20.
- I click to sell Knarr a Ruby and select 19 from the slider. The message pops up saying "sold 1 Ruby for 20 x380".
- I check my inventory and see I now have 1 Ruby left and 380 Coins. I check Knarr's Buy inventory and he now only has 1 Ruby when I sold him 19.

**To Reproduce**

1.  Go Find Knarr
2.  Sell him an item you hold a stack of 
3.  Choose any volume of the stack to sell him
4.  Choose OK to complete the sale
5.  Notice the held volume by Knarr after buying does not reflect volume purchased from player 

**Expected behavior**
Knarr should reflect the purchased items volume against his own stores inventory count.

**Desktop (please complete the following information):**
 - Bepinex version: 5.4.2100
 - KnarrTheTrader version: 0.4.0
 - Client (Local Play)

**Additional context**
I did a few other tests with different amounts and it seems like the amount he gains from the sale is the same as the amount left in my inventory and not the amount I sold him each time. I do get the correct amount of gold for the number of items I selected to sell though. Tested on both a singleplayer world I'd played before and a completely fresh world/character with nothing but Knarr and Bepinex installed. I am using Vortex for my mod manager if that matters.

**Comment by insanepinky** [comment]
Local Gameplay. I don't have a server to test on unfortunately. I forgot to add I'm also on the latest Valheim version if that matters.

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/MonoScripts/OdinStore.cs#L1192

Pinning here, I believe this is the culprit

**Comment by sbtoonz** [comment]
> Local Gameplay. I don't have a server to test on unfortunately. I forgot to add I'm also on the latest Valheim version if that matters.

To clarify based on the report

This output only happens when using the slider to select X to sell to knarr 

Not when selling 1 single item?

**Comment by insanepinky** [comment]
Just double checked and it is only happening when using the slider. Having only 1 Ruby in my inventory and selling it to him without the slider didn't have the issue. He only gained 1 Ruby and the message had the right amount too.

**Comment by sbtoonz** [comment]
2752dda5a3fafc283f2b45ed4d0a1e8f374d7426

**Comment by sbtoonz** [comment]
[Trader20_TestVer.zip](https://github.com/sbtoonz/Trader_2.0/files/11033442/Trader20_TestVer.zip)
Please Test this version and see if the bug persists

**Comment by insanepinky** [comment]
Bug is still happening, exact same behavior as before. Tested on the same character/world I had used to test before and a fresh character/world (just in case something was stuck in the save). Same result on both.

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/Trader_2.0/commit/ebc3a4811f086fcdc3a8b147fd14228fa7f362c4

**Comment by sbtoonz** [comment]
@insanepinky 
https://github.com/sbtoonz/Trader_2.0/releases/tag/v0.4.1-beta

99.9% sure it is fixed now

**Comment by sbtoonz** [comment]
Confirmed solved in my gameplay please confirm solved in your gameplay and I will close the issue

**Comment by insanepinky** [comment]
Can confirm Knarr is gaining the correct amount of items in his inventory now. However, the message that pops up after selling the items is still saying the wrong number of items sold (but the correct number of gold for the items actually sold). For example: Selling 1 Ruby from a full stack of 20 gives the message "Sold 19xRuby for 20 x20" and selling 14 Ruby from a full stack of 20 gives the message "Sold 6xRuby for 280 x280".

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/MonoScripts/OdinStore.cs#L1199

putting here so i can fix when im off work

Culprit is this line of code I neglected to reflect the proper slider value change into the broadcasted message to the player

**Comment by sbtoonz** [comment]
can confirm a69d8b4 solves your issue in it's entirety
