### ISSUE TITLE
[BUG] - Knarr cannot resolve YML when installed through R2/Thunderstore

### ISSUE THREAD

**Issue by awdwyn** [sbtoonz/Trader_2.0#18]
Continuing from the discord thread: https://discord.com/channels/252172638670028803/1087170976401338468

Updated server and client to 0.4.1 but still not able to get anything to show up in Knarrs buy/sell window (see screenshot)

![image](https://user-images.githubusercontent.com/23404043/227385342-7906b975-eb66-4528-9d1d-ec4ee7578d91.png)

No errors or relevant information in the log file.

Installed client mods (server has only what's needed, the client-only mods are removed):

Dependency string list

denikson-BepInExPack_Valheim-5.4.2100
Smoothbrain-Jewelcrafting-1.4.6
Smoothbrain-CreatureLevelAndLootControl-4.5.5
Smoothbrain-InstantEquip-1.0.5
Smoothbrain-Cooking-1.1.11
Smoothbrain-Resurrection-1.0.5
Smoothbrain-Blacksmithing-1.2.2
Smoothbrain-PassivePowers-1.0.9
Smoothbrain-Farming-2.1.8
Smoothbrain-SteadyRegeneration-1.0.1
Smoothbrain-Tenacity-1.0.2
Smoothbrain-Evasion-1.0.2
Smoothbrain-Vitality-1.1.0
Smoothbrain-StaminaRegenerationFromFood-1.5.3
Smoothbrain-PackHorse-1.0.2
Smoothbrain-Building-1.2.4
Smoothbrain-Lumberjacking-1.0.3
Smoothbrain-Ranching-1.1.1
Smoothbrain-Mining-1.1.3
Smoothbrain-Sailing-1.1.5
Smoothbrain-SmoothSave-1.0.0
Smoothbrain-DisableCameraPanning-1.0.0
hyleanlegend-Rune_Magic-1.1.17
Azumatt-Official_BepInEx_ConfigurationManager-18.0.0
Atopy-QuickPing-1.5.7
Advize-PlantEverything-1.13.3
Azumatt-AzuAreaRepair-1.0.1
aedenthorn_nexus-ShowContainerContents-0.3.0
ValheimModding-Jotunn-2.11.0
MSchmoecker-PressurePlate-0.8.1
ComfyMods-LicenseToSkill-1.1.1
MathiasDecrock-Snap_Points_Made_Easy-1.3.2
digitiliad-NotificationTweaks-0.3.2
Azumatt-Build_Camera_Custom_Hammers_Edition-1.1.3
coemt-Belts-1.0.6
ComfyMods-Gizmo-1.5.1
digitiliad-HotbarSwitch-0.1.1
RandyKnapp-MinimalStatusEffects-1.0.3
Korppis-SolidHitboxes-1.0.4
Goldenrevolver-Instantly_Destroy_Boats_And_Carts-1.0.3
WackyMole-WackysDatabase-1.4.2
JereKuusela-Projectile_Collision-1.2.0
JereKuusela-Smoke_Collision-1.5.0
Fragnarok-ImmersiveCompass-1.1.2
Azumatt-DeezMistyBalls-1.0.1
HugotheDwarf-More_and_Modified_Player_Cloth_Colliders-3.1.0
Smoothbrain-Foraging-1.0.3
pipakin-SkillInjector-1.1.1
urgemeuwu-Wagon_Skill-1.0.0
Azumatt-AzuWorkbenchTweaks-1.0.1
Azumatt-ImFRIENDLY_DAMMIT-1.0.8
Digitalroot-Max_Dungeon_Rooms-2.0.9
blacks7ar-SNEAKer-1.0.7
We_Haul-Zero_Cost_Sneaking-1.0.0
Smoothbrain-Groups-1.1.15
Smoothbrain-Network-1.0.1
JereKuusela-Server_devcommands-1.44.0
JereKuusela-Upgrade_World-1.34.0
blacks7ar-BowPlugin-1.3.9
JustMennowar-BeehiveUtils_Revived-1.0.2
aedenthorn_nexus-AutoFeed-0.7.0
blacks7ar-MagicPlugin-1.3.1
NoPetRides-NoPetRides_ModUtils-1.0.0
NoPetRides-CropUtils-1.2.1
RandyKnapp-AdvancedPortals-1.0.3
Smoothbrain-TargetPortal-1.1.6
Therzie-Warfare-1.3.9
Azumatt-AzuAutoStore-1.0.2
MSchmoecker-MultiUserChest-0.4.3
KGvalheim-Soulcatcher_JC_KG_Additions-4.4.1
PhantomGamers-PreventAccidentalInteraction-1.0.9
Azumatt-AzuClock-1.0.0
Azumatt-MagicEitrBase-1.1.3
nearbear-CustomSlotItemLib-1.0.4
nearbear-WishboneSlot-1.0.3
GemHunter1-FastTeleport-1.1.0
Crystal-Pathfinder-2.0.7
blacks7ar-VikingsDoSwim-1.1.4
Rabid_Wolf_Studios-Climbing-1.0.5
Tequila-Dvergr_Pieces-2.0.1
BentoG-MissingPieces-2.0.1
VentureValheim-No_Seasonal_Restrictions-0.1.5
RoundStone-RoundStoneScrollFirstPerson-1.0.0
Azumatt-Recipe_Description_Expansion-1.0.0
MadBuffoon-WeightBase-1.1.0
Goldenrevolver-Sorted_Menus_Cooking_Crafting_and_Skills_Menu-1.2.2
ComfyMods-SearsCatalog-1.2.0
Azumatt-AzuExtendedPlayerInventory-1.0.4
MSchmoecker-HammerTime-0.3.3
TrisTris-LocateEverything-1.0.2
OdinPlus-OdinCampsite-1.5.0
ASharpPen-Drop_That-2.3.5
aedenthorn_mods-InstantMonsterLootDrop-0.5.0
Azumatt-ResourceUnloadOptimizer-1.0.1
blacks7ar-SapExtractor-1.0.5
Azumatt-RunningStaminaBase-1.0.2
OdinPlus-TeleportEverything-2.3.1
Therzie-Monstrum-1.0.5
JereKuusela-Item_Stand_All_Items-1.17.0
zamboni-Gungnir-1.7.1
Neobotics-WolfPack-1.0.2
JereKuusela-Server_Sync_Fix-1.2.0
RobinHood-Candles_LanternsANDbeeswaxx_02050-0.0.1
TastyChickenLegs-BedRules-1.0.1
Vystyk-ValheimDefenders-0.2.4
TastyChickenLegs-TimedTorchesStayLit-1.3.2
TastyChickenLegs-AutomaticFuel-1.3.5
TastyChickenLegs-RecyclePlus-1.2.2
JereKuusela-Render_Limits-1.5.0
JereKuusela-Ruler-1.2.0
JustMennowar-LuckyBranches-1.0.2
OdinPlus-OdinsHorsePen-1.0.4
Meldurson-AllTameableTamingOverhaul-1.1.3
cdymrtn-BuildRestrictionTweaks-0.3.0
OdinPlus-CraftyCartsRemake-3.0.8
MSchmoecker-FenceSnap-0.2.0
MrSerji-Construction-0.2.5
OdinPlus-OdinArchitect-1.2.7
ValheimModding-HookGenPatcher-0.0.3
MathiasDecrock-SeedTotem-4.2.1
OdinPlus-CrystalLights-1.0.7
MSchmoecker-VNEI-0.10.0
blacks7ar-FoodEitrRegen-1.0.1
blacks7ar-CombatOverhaulREwrite-1.0.8
Laudriel_Mods-LeviathanNeverGoesAway-0.0.1
Azumatt-NoHoeDust-1.0.3
Azumatt-NoCultivatorDust-1.0.3
Azumatt-NoBuildDust-1.0.3
TastyChickenLegs-TreesReborn-1.0.2
ComfyMods-Pinnacle-1.2.3
OdinPlus-GoodestBoy-0.1.6
FixItFelix-GrassTweaks_By_Aedenthorn-0.2.0
Nonnnnne-Panocs_HD_Map-1.0.0
KibCorgi-CustomGraphicsSettingsByAedenthorn-0.7.1
MerryValheimMods-NoStumps-1.0.0
Korppis-Spearfishing-1.0.1
Azumatt-Minimal_UI-2.1.9
Marf-FuelEternal-1.2.0
ASharpPen-Fall_Damage_For_Creatures-1.1.0
Pfhoenix-Fartheim-1.2.0
Pfhoenix-ODINFLIGHT-1.3.0
Digitalroot-Heightmap_Unlimited_Remake-1.3.6
Azumatt-AzuHoverStats-1.0.6
ComfyMods-Enhuddlement-1.1.0
Azumatt-WardIsLove-3.0.9
Goldenrevolver-Teleport_Instantly_Updates_Weather_And_Removes_Wet_Debuff-1.0.1
GoldenJude-WeatherStones-0.1.2
Balrond-balrond_shipyard-1.1.5
Azumatt-Where_You_At-1.0.7
OdinPlus-PlantIt-0.1.5
Azumatt-AzuContainerSizes-1.0.1
Thordomr-More_Gates-1.0.10
OdinPlus-OdinsTraps-1.1.8
Azumatt-GiveEmTheBoot-1.0.1
ComfyMods-Chatter-1.4.1
blacks7ar-WeaponHolsterOverhaul-1.0.5
Enta-MuchBetterHotkeys-1.1.0
OdinPlus-KnarrTheTrader-0.4.1
Azumatt-FastLink-1.3.5
Goldenrevolver-Obtainable_Stone_Pickaxe_and_Upgradeable_Antler_Pickaxe-1.0.0
Desires-MoreUpgrades-1.0.0
Vapok-AdventureBackpacks-1.6.15
LVH-IT-UseEquipmentInWater-0.2.3
Therzie-Armory-1.0.3
cazou-QuickerStack-0.0.5
Azumatt-Third_Eye-2.0.3
aedenthorn-Craft From Containers-3.1.2
williammetcalf-Useful Armor Stands-1.0.4
makail-ItemDrawers-0.5.0

**Comment by sbtoonz** [comment]
I will have to sift through your mods because I was unable to replicate this behavior with only knarr living on the server and the client

**Comment by sbtoonz** [comment]
please attach player log from the time you click "join server" to the time you spawn into the world

also attach that corresponding server side log 

Thank you

**Comment by awdwyn** [comment]
Ok - what level in the bepinex logging would you like? everything including IL?

**Comment by sbtoonz** [comment]
> Ok - what level in the bepinex logging would you like? everything including IL?

please exclude the IL stuff it makes the log hard to read for what I want to validate

I am specifically looking at for the log section where it sends the ServerSync mod configs from every mod that uses serversync to the client

**Comment by awdwyn** [comment]
Excluded IL but it seems like it's in there anyway? I dunno...

_Player.Log_: Began connection to server at log line 123366
Server _LogOutput.log_: Began connection from client at log line 112518
[Player.log](https://github.com/sbtoonz/Trader_2.0/files/11057261/Player.log)
[LogOutput.log](https://github.com/sbtoonz/Trader_2.0/files/11057262/LogOutput.log)

**Comment by sbtoonz** [comment]
```
[Debug  :KnarrTheTrader] System.NullReferenceException: Object reference not set to an instance of an object
  at OdinStore+<ReadStoreItems>d__62.MoveNext () [0x0007f] in <9ca445a3cef64c89b6c6d217097861f1>:0 
```
on the player log

can you please post trader_config.yaml from the server?

**Comment by awdwyn** [comment]
Acorn:
    cost: 3
    stack: 1
    inventory count: 3
    purchase price: 1

Amber:
    cost: 15
    stack: 1
    inventory count: 5
    purchase price: 5

AmberPearl:
    cost: 30
    stack: 1
    inventory count: 5
    purchase price: 10

Ruby:
    cost: 60
    stack: 1
    inventory count: 5
    purchase price: 20

SilverNecklace:
    cost: 90
    stack: 1
    inventory count: 5
    purchase price: 30

**Comment by sbtoonz** [comment]
can you also post what is on client side?

**Comment by awdwyn** [comment]
Its empty as comes fresh installed off thunderstore.

**Comment by sbtoonz** [comment]
> 

Can you try putting a single object in the one that is on the client side it does not need to match the server in any way shape or form. 
Repeat the server login process 

Attach the log from said actions

Thank you so much for your time in advance

**Comment by awdwyn** [comment]
You bet

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/Trader_2.0/blob/master/Trader2.0/MonoScripts/OdinStore.cs#L311

putting here for notes

I need to add a check for _storeinventory.Count() <=0 return;

**Comment by awdwyn** [comment]
[Player.log](https://github.com/sbtoonz/Trader_2.0/files/11057332/Player.log)
[LogOutput.log](https://github.com/sbtoonz/Trader_2.0/files/11057333/LogOutput.log)

**Comment by awdwyn** [comment]
Disconnect on version mismatch but none of the listed mods show a bad version - will pop the dll on the server - 1 sec

**Comment by sbtoonz** [comment]
> Disconnect on version mismatch but none of the listed mods show a bad version - will pop the dll on the server - 1 sec (restarting server now)
> 
> It loaded with dll on client and server - client player.log attached. Multiple login attempts in this log - the one you're looking for starts around line 3700. Error is at line 5030. [Player.log](https://github.com/sbtoonz/Trader_2.0/files/11057421/Player.log)

are you using some modpack I can download to test against?

**Comment by awdwyn** [comment]
I'm afraid not - it's a mix of stuff off the thunderstore and nexus

**Comment by awdwyn** [comment]
I wonder if I can package it up and put the plugins and configs on dropbox for you

**Comment by sbtoonz** [comment]
> I wonder if I can package it up and put the plugins and configs on dropbox for you

https://valheim.thunderstore.io/package/JereKuusela/Server_Sync_Fix/

Are you able to also install this mod

I am curious to see the report of which versions of serversync are in use here

**Comment by awdwyn** [comment]
I already have that server sync fix installed.

**Comment by sbtoonz** [comment]
then I will have to download all your mod and check them 1:1 because I am unable to replicate this behavior with only knarr

**Comment by awdwyn** [comment]
Ok here you go - if you give me your steam64 id I'll add you to authorized users and you can try logging into the dedi for testing
[](https://www.dropbox.com/s/u3mtzrbhqwkkh4l/config.7z?dl=0)
[](https://www.dropbox.com/s/r0bvry0md20tk39/plugins.7z?dl=0)

**Comment by sbtoonz** [comment]
I am honstly impressed you get to the login screen with this mod setup.. the volume of "cannot load" and Null references I have seen so far is insane

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/227396735-1a9e002b-188d-43af-8a17-667767e6a033.png)
I am still waiting to see if i can get the start screen

**Comment by awdwyn** [comment]
> I am honstly impressed you get to the login screen with this mod setup.. the volume of "cannot load" and Null references I have seen so far is insane

Somethings wrong then - I get zero errors normally.. I wonder if you're missing something I have

**Comment by awdwyn** [comment]
hmm... hookgenpatcher might be missing a bit

**Comment by sbtoonz** [comment]
I grabbed both the links you supplied and placed them in my client
[LogOutput.log](https://github.com/sbtoonz/Trader_2.0/files/11057506/LogOutput.log)
My client log 



and the server log
[LogOutput.log](https://github.com/sbtoonz/Trader_2.0/files/11057508/LogOutput.log)

**Comment by awdwyn** [comment]
[BepInEx.zip](https://github.com/sbtoonz/Trader_2.0/files/11057517/BepInEx.zip)
try with this in the bepinex folder - i wonder if HookGenPatcher was killing it...

**Comment by sbtoonz** [comment]
no its keymanager... let me ... shoot blaxx a DM see if she can help with a sandbox to test this issue in

**Comment by awdwyn** [comment]
Ok - Therzies mods are the premium ones, Warfare and Monstrum. If it simplifies things I am getting the same results in singleplayer as I do connecting to the server.

**Comment by awdwyn** [comment]
Disabled all mods except BepInEx, Jotunn, and Knarr - using a local character as I disabled mods. The issue persists. Let me share the character file and see if that gives you any insight? I fear one of those mods has changed the character file and done something to it's inventory which breaks Knarr.

[localadmin.zip](https://github.com/sbtoonz/Trader_2.0/files/11057662/localadmin.zip)

**Comment by awdwyn** [comment]
Hmm weird. Okay. Brand new world and brand new character. Turned on devcommands and 'spawn Knarr', to find the same result as before. Only have bepinex and knarr installed.

**Comment by sbtoonz** [comment]
What's your discord I would like to get ona video call and show you what I experience vs what you experience 

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://discord.gg/P9CgP3UqyC" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/discord.svg" alt="zarboz#7828" height="30" width="40" /></a>
</p>

**Comment by awdwyn** [comment]
I'm Sidelia - you're zarboz?

**Comment by sbtoonz** [comment]
after brief video screen sharing it was discovered that Knarr fails to resolve the YML path when game is launched through R2ModMan 

This is very odd becaus the path resolution is granted via the BepinEX api 
[BepinEx Paths Class Documentation](https://docs.bepinex.dev/api/BepInEx.Paths.html)

That means either the deployment methodology of BepinEx via R2/Thunderstore inhibits this resolution or similar.

**Comment by sbtoonz** [comment]
failed to resolve because i was using / instead of [72c0daf](https://github.com/sbtoonz/Trader_2.0/commit/72c0dafb95551492f3125e324a47a1dfc62de4a8)
