### ISSUE TITLE
[BUG] - Friends can't sell items 

### ISSUE THREAD

**Issue by Skekiam** [sbtoonz/Trader_2.0#20]
**Describe the bug**
My friends can't sell items (I'm the host of a non-dedicated serve). I'm able to buy and sell items, but they're only able to buy them. I figured that maybe only the host is able to do this, but wanted to confirm anyway.

**To Reproduce**
1. Talk to Knarr while having sellable items in inventory (as a non host player)
2. Go to the Sell Tab
3. Select the appropriate item to sell
4. Click the sell button
5. Nothing happens

**Expected behavior**
I expected all players to be able to sell items to the Trader.

**Screenshots**
![KnarrBug](https://user-images.githubusercontent.com/129338562/228682214-a7a2d24a-bd72-4c47-9548-2766929c76c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 22]: Not sure of what this is referring to? I'll assume the mod itself: 0.4.3
 - Bepinex Version: 5.4.21.0
 - Valheim Version: 0.214.300
 - Server or Client: Non-Dedicated Server hosted by me

**Comment by sbtoonz** [comment]
Are you hosting via the game or on a hosting service like gportal or
similar ?

**Comment by sbtoonz** [comment]
Ah your non dedi hosting

I will inspect this issue I only tested with dedicated server hosting and
in single player

**Comment by sbtoonz** [comment]
@Skekiam  do you have a discord or other means I can contact you? I would need someone to test this with since the only way I could test is single player or dedicated server.

**Comment by Skekiam** [comment]
@sbtoonz Hi, thank you so much for the quick responses!

Yes I do, it's Sekiam#7401 I can't test stuff at this moment and I'm not sure of how to obtain the logs (I've closed the server since) but I'll be free tomorrow afternoon, you can add me in Discord and I'll PM you when I'm available!

Cheers!
